### ISSUE TITLE
Unable to post pic/ video to space and channel

### ISSUE THREAD

**Issue by DianaDai-meh** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#95] opened 2021-02-10 05:10 UTC

**Comment by JalenYes** [comment] 2021-02-10 06:51
The issue is fixed.

**Comment by JalenYes** [comment] 2021-02-10 07:31
Can't upload a pic/video 
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/40333215/107478773-06c01100-6b48-11eb-9ee7-971240a21fe7.png">
<img width="866" alt="image" src="https://user-images.githubusercontent.com/40333215/107478788-0f184c00-6b48-11eb-9286-0ca09fe0305a.png">

**Comment by JalenYes** [comment] 2021-02-10 18:24
This is fixed by Yuchen.

**Closed by JalenYes** 2021-02-10 18:24 UTC
Labels: Priority: High, bug
